---
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      sh -c '
        set -euo pipefail
        # Use $$ to prevent interpolation 
        if [ $$(id -u) -ne 1000 ]; then
          exit 1
        fi
        aspell --version # aspell
        awk --version # gawk
        base64 --version # coreutils
        curl --version # curl
        dasel --version # dasel
        git --version # git
        grep --version # grep
        java --version # openjdk21-jre-headless
        jf -v # jsonfmt
        mvn --version # maven
        pandoc --version # pandoc
        pip --version # py3-pip
        pipx --version # pipx
        prettier --version # prettier
        python --version # python3
        remarshal --version # remarshal
        xmlindent -v # xmlindent
        xmllint --version # libxml2-utils
        xmlsec1 --version # xmlsec
        xmlstarlet --version # xmlstarlet
        xmlto --version # xmlto
        xsltproc --version # libxslt
        yq --version # yq-go
      '
