---
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      sh -c '
        set -euo pipefail
        # Use $$ to prevent interpolation 
        if [ $$(id -u) -ne 1000 ]; then
          exit 1
        fi
        base64 --version # coreutils
        curl --version # curl
        git --version # git
        pip --version # py3-pip
        pipx --version # pipx
        python --version # python3
        yq --version # yq
        xmllint --version # libxml2-utils
        xsltproc --version # libxslt
        mvn --version # maven
        java --version # openjdk21-jre-headless
        xmlindent -v # xmlindent
        xmlsec1 --version # xmlsec
        xmlstarlet --version # xmlstarlet
        xmlto --version # xmlto
      '
